version: '3.8'

name: docker-nginx-mysql

services:
  nginx:
    image: nginx:alpine
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - "./html:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - my_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf

  mysql:
    image: mysql:8.0
    container_name: my_mysql_new
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf  # Pastikan file custom.cnf dimuat ke dalam direktori konfigurasi MySQL
      - "mysql_data:/var/lib/mysql"
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local

configs:
  nginx_config:
    file: ./nginx.conf
  mysql_config:
    file: ./mysql/custom.cnf